name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  mysql:
    name: ${{ format('MySQL {0} ({1}, Ruby {2})', matrix.db_version, matrix.distribution, matrix.ruby) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db_version: ["8.0", "8.4", "9.5"]
        distribution: ["debian:bookworm", "ubuntu:noble", "ubuntu:jammy", "ubuntu:focal"]
        ruby: ["4.0"]
        include:
          - distribution: "debian:bookworm"
            mysql: "8.0"
            ruby: "3.3"
          - distribution: "ubuntu:jammy"
            mysql: "8.0"
            ruby: "3.3"
    steps:
    - uses: actions/checkout@v6
    - name: docker login
      run: echo $GITHUB_TOKEN | docker login ghcr.io --username trilogy --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      env:
        DB_VENDOR: mysql
        DB_VERSION: ${{ matrix.db_version }}
        DISTRIBUTION: ${{ matrix.distribution }}
        RUBY_VERSION: ${{ matrix.ruby }}
      run: script/cibuild

  mariadb:
    name: ${{ format('MariaDB {0} ({1}, Ruby {2})', matrix.db_version, matrix.distribution, matrix.ruby) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db_version: ["10.6", "10.11", "11.4", "11.8", "12.1"]
        distribution: ["debian:bookworm", "ubuntu:noble", "ubuntu:jammy", "ubuntu:focal"]
        ruby: ["3.3", "3.4"]
    steps:
    - uses: actions/checkout@v6
    - name: docker login
      run: echo $GITHUB_TOKEN | docker login ghcr.io --username trilogy --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      env:
        DB_VENDOR: mariadb
        DB_VERSION: ${{ matrix.db_version }}
        DISTRIBUTION: ${{ matrix.distribution }}
        RUBY_VERSION: ${{ matrix.ruby }}
      run: script/cibuild
